### ISSUE TITLE
Variation of the template - handlebars help

### ISSUE THREAD

**Issue by danieltomasz** [bingryan/obsidian-ibook-plugin#22]
Great idea for a plugin!

I have a question, I dont know the templating language good enough.

Currently the annotation has the form (included template)
```
- section 1
	- annotation A
 - section 1
	-  annotation B
 - section  2
	- annotation C
```

I would like to have following effect
```
- section 1
	 - annotation A
	 - annotation B
 -  section 2
	 -  annotation C
```
how to access previous item in handlebars and compare value of `ZFUTUREPROOFING5`, and add  value of `ZFUTUREPROOFING5` to file  only if it  is different from the previous one? 
I need to write a custom helper? I never used handlebars/js.

**Comment by bingryan** [comment]
@danieltomasz hey danieltomasz, Thank you for your issue, I have used your format as the default template, I think most people should want this template. 

```
- section 1
	- annotation A
	- annotation B
-  section 2
	-  annotation C
-  section 3
	-  annotation D
		- commit AA
	-  annotation E
		- commit BB
```

**Comment by bingryan** [comment]
updated 🤓

**Comment by bingryan** [comment]
> Thanks! When I try to update plugin via BRAT I received this info
> 
> ```
> The release is not complete and cannot be downloaded. main.js is missing from the today release
> ```

ci error , i fixed it.

**Comment by bingryan** [comment]
try again

**Comment by danieltomasz** [comment]
Thanks, it work now as I requested :) The issue might be closed :) 

One last thing, I observed  that in the template there is this line
`# 🔍 How I Discovered IT`, this line is left in the template by omission? :)

**Comment by bingryan** [comment]
> Thanks, it work now as I requested :) The issue might be closed :)
> 
> One last thing, I observed that in the template there is this line `# 🔍 How I Discovered IT`, this line is left in the template by omission? :)

you can delete it by plugin setting, this is title :)
