### ISSUE TITLE
Problem with accents and tildes in heading

### ISSUE THREAD

**Issue by marconoris** [bingryan/obsidian-ibook-plugin#36]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/17103684/227731813-9f94b49b-9c96-4aa4-ab14-5eadf56f7f3b.png">

A small thing. Is the heading of an exported book...

**Comment by bingryan** [comment]
@marconoris   what is it actually displayed(ibook), and what is it like after export(obsidian markdown)?

**Comment by marconoris** [comment]
*"L'idiota** is book name in Apple Books and **L&#x27;idiota** is h1 obsidian markdown in note after export...

**Comment by bingryan** [comment]
@marconoris update, and try again :)

**Comment by marconoris** [comment]
Uh! Same issue with 2.0.2 version (and I restarted Obsidian too)

**Comment by bingryan** [comment]
@marconoris update, and try again 🤣

**Comment by marconoris** [comment]
don't work 😅

**Comment by bingryan** [comment]
but, my local test is ok. Did you update the plugin: 2.0.3

**Comment by bingryan** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/41174435/228566809-2a0792e1-3ae9-48ea-8db7-16d6f462e140.png">
view is ok

**Comment by marconoris** [comment]
Yes I have 2.0.3 version... is just a small issue, view is ok 👍🏻
