### ISSUE TITLE
Would you consider supporting the delta sync/incremental backup feature?

### ISSUE THREAD

**Issue by maymaymaybe8** [bingryan/obsidian-ibook-plugin#40]
The current plug-in is very good 👍🏻, but the original folder must be deleted every time it is imported, and it cannot be overwritten or incrementally synchronized on the existing basis.

I hope you will consider supporting the delta sync feature.
1. The same book, updated to the latest highlights and notes.
2. When the highlights and notes of the book have not changed, do not adjust.

If a book is deleted in iBooks, the highlights and annotations of the deleted book will be hidden when the plug-in is used to reimport all books. 
It is hoped that the highlights and annotations will not be adjusted during incremental synchronization.

**Comment by bingryan** [comment]
for your description, I will try to implement them  :)

**Comment by bingryan** [comment]
> Thanks. Maybe you can refer to the delta sync feature of this [plug-in](https://github.com/atfzl/obsidian-apple-books-plugin).
> 
> After trial, I found its delta sync feature is adequate, but it would not retain the annotations of previously read but deleted books.
> 
> The annotations in the .sqlite table will not be discarded even if the book is deleted. Therefore, I think the feature of retaining historical annotations can also be realized.(not sure, I guess)

yes, The annotations not be delete even if the book is deleted.

**Comment by bingryan** [comment]
I have to deal with other things recently, maybe start working on it next week :)

**Comment by bingryan** [comment]
> Excellent, I am eagerly anticipating it.❤️

I'm very sorry, I have been busy with an AI client before, and I will deal with this problem next, :)

**Comment by bingryan** [comment]
> the original folder must be deleted every time it is imported

this logic does not appear, current is:

1. The export directory (ibook) will be created if it does not exist
2. Import each book with annotations/hightlights into the export directory(file name is the same as the book name)
3. if there is already a file with the same book name, the book will not be imported again

**Comment by bingryan** [comment]
> Maybe you can refer to the delta sync feature of this [plug-in](https://github.com/atfzl/obsidian-apple-books-plugin).
i have read this plugin code , It has no content delta sync.

**Comment by bingryan** [comment]
For content delta sync. Can you consider: https://github.com/bingryan/obsidian-ibook-plugin#export-single-book-by-search

It will be on your mouse cursor and start importing the entire content, then you can select content you want into add.
