### ISSUE TITLE
Bug: No book page created when ':' is in book title

### ISSUE THREAD

**Issue by MinMaxing** [bingryan/obsidian-ibook-plugin#44]
Hello!

Let me preface by thanking the developer for making this plugin. It greatly enhances my obsidian experience.

I found a small bug. Whenever a book title contains a ':', no book page will be created when the export command is called. This is likely due to the book title not being sanitized and/or Obsidian not accepting ':' in a note title.

To @bingryan, consider sanitizing the book title; or making a check in export.ts that checks for forbidden characters in note titles.

To users, a temporary override can be created either in export.ts (line 100) when building from source or in the obsidian config file when it's already downloaded (line 47084 in main.js). Replace `${contentname}.md` with `overide.md`. You can then import books with ':' in the title, and then manually changing the title as all new imports will be named override.md.

**Comment by bingryan** [comment]
Got it

**Comment by bingryan** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/41174435/236493045-83e6382e-8142-45ef-a97c-89268b2a9dcb.png">
@MinMaxing  i add toggle for this feat. please update this plugin and try again :)

**Comment by MinMaxing** [comment]
Updated and works perfectly. Marked as closed!

**Comment by Amparose** [comment]
This still breaks the front-matter metadata in the md file:

```yaml
title: Example: That breaks the front matter
```

Instead of how the file name sanitises:

```yaml
title: Example- That breaks the front matter
```
