### ISSUE TITLE
help request: highlighted text's color. 

### ISSUE THREAD

**Issue by ichhh** [bingryan/obsidian-ibook-plugin#46]
Thank you for your plugin.
I'm trying to modify it a bit to import to obsidian text with it's highlighted color (yellow, blue...) but failing to find the parameter.
Could you please help me out?

**Comment by bingryan** [comment]
> Thank you for your plugin. I'm trying to modify it a bit to import to obsidian text with it's highlighted color (yellow, blue...) but failing to find the parameter. Could you please help me out?

https://github.com/bingryan/obsidian-ibook-plugin/blob/master/docs/example.md

**Comment by bingryan** [comment]
Or are you talking about the highlight color that comes with the ibook?

**Comment by bingryan** [comment]
```
---
tags:
- ibook/
---

# 📔 Book: {{library.ZSORTTITLE}}

**Author**:: {{library.ZAUTHOR}}

**LANGUAGE**:: {{library.ZLANGUAGE}}

**Book Link**:: [Apple Books Link](ibooks://assetid/{{library.ZASSETID}})

{{#if library.ZBOOKDESCRIPTION}}
---
# 🧾 Description
	{{{library.ZBOOKDESCRIPTION}}}
{{/if}}

---
# 🔍 How I Discovered IT

{{#group annotation by="ZFUTUREPROOFING5"}}
- 📚{{value}}
	{{#each items}}
	{{#if ZANNOTATIONSELECTEDTEXT}}
	{{#is ZANNOTATIONSTYLE 5}}
	- 🎯 <mark style="background: #C4B3D9;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{#is ZANNOTATIONSTYLE 4}}
	- 🎯 <mark style="background: #E6A5AB;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{#is ZANNOTATIONSTYLE 3}}
	- 🎯 <mark style="background: #EDD570;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{#is ZANNOTATIONSTYLE 2}}
	- 🎯 <mark style="background: #A8BADE;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{#is ZANNOTATIONSTYLE 1}}
	- 🎯 <mark style="background: #B0D17F;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{#is ZANNOTATIONSTYLE 0}}
	- 🎯 <mark style="background: #E65747;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
	{{/is}}
	{{/if}}
		{{#if ZANNOTATIONNOTE}}
		- ✍️{{ZANNOTATIONNOTE}}
		{{/if}}
	{{/each}}
{{/group}}
```

if you want to use ibook highlighted text's color. set this template : `setting-> ibook -> template`

<img width="663" alt="image" src="https://user-images.githubusercontent.com/41174435/236677378-329b5c36-9a90-4f14-b9d8-62bf3fb81c0e.png">
