### ISSUE TITLE
Why won't a certain book import?

### ISSUE THREAD

**Issue by wealthychef1** [bingryan/obsidian-ibook-plugin#49]
Hello, 
I was able to import four books to my Obsidian vault, lovely.  Canceling Readwise in 4... 3... 2... 
However on the fifth book, it just seemed to silently fail. 
There are many highlights in the book, and it's the same format as the others, which is epub, but it just doesn't show up in the target folder. 
How can I troubleshoot this please?  
Thanks for any guidance

**Comment by bingryan** [comment]
Can you search for your book through [export-single-book-by-search](https://github.com/bingryan/obsidian-ibook-plugin#export-single-book-by-search)

**Comment by bingryan** [comment]
delelte `ibook` dir, and try again.

you can open `view-> Toggle Developer Tools`, Check to see if there are five records like:
```
$ echo "
		SELECT 
			DISTINCT ZASSETID
		FROM ZBKLIBRARYASSET
	" | sqlite3  xxxxxxx
```

**Comment by wealthychef1** [comment]
> Can you search for your book through [export-single-book-by-search](https://github.com/bingryan/obsidian-ibook-plugin#export-single-book-by-search)

Yes and that is in fact how I'm doing this... is there a bulk import?

**Comment by wealthychef1** [comment]
> delelte `ibook` dir, and try again.
> 
> you can open `view-> Toggle Developer Tools`, Check to see if there are five records like:
> 
> ```
> $ echo "
> 		SELECT 
> 			DISTINCT ZASSETID
> 		FROM ZBKLIBRARYASSET
> 	" | sqlite3  xxxxxxx
> ```

No but there is this when I try to import the book.  It is indeed a lengthy book, is it hitting a word/character limit?  
<img width="821" alt="2023-05-13 17 46 42 CleanShot Obsidian" src="https://github.com/bingryan/obsidian-ibook-plugin/assets/4825448/1d11912e-7670-4c77-9ccb-cd2ff1fab98e">

**Comment by bingryan** [comment]
> export-single-book-by-search

https://github.com/bingryan/obsidian-ibook-plugin#export-all

**Comment by bingryan** [comment]
> > Can you search for your book through [export-single-book-by-search](https://github.com/bingryan/obsidian-ibook-plugin#export-single-book-by-search)
> 
> Yes and that is in fact how I'm doing this... is there a bulk import?

https://github.com/bingryan/obsidian-ibook-plugin#export-all

**Comment by bingryan** [comment]
> > delelte `ibook` dir, and try again.
> 
> I did this and it had no apparent effect.
> 
> > you can open `view-> Toggle Developer Tools`, Check to see if there are five records like:
> > ```
> > $ echo "
> > 		SELECT 
> > 			DISTINCT ZASSETID
> > 		FROM ZBKLIBRARYASSET
> > 	" | sqlite3  xxxxxxx
> > ```
> 
> There are not those records, but there is this when I try to import the book. It is indeed a lengthy book, is it hitting a word/character limit? <img alt="2023-05-13 17 46 42 CleanShot Obsidian" width="821" src="https://user-images.githubusercontent.com/4825448/238129597-1d11912e-7670-4c77-9ccb-cd2ff1fab98e.png">

default 200KB, For your issue, I should increase the buffer :)

**Comment by bingryan** [comment]
@wealthychef1 update this plugin, try again :)

batch : https://github.com/bingryan/obsidian-ibook-plugin#export-all
single:  https://github.com/bingryan/obsidian-ibook-plugin#export-single-book-by-search

**Comment by wealthychef1** [comment]
Confirmed fixed!  Thank you.  I'll check into the mass export soon.  
I have an existing spreadsheet which I exported to CSV.  
I want to combine my notes with the ibooks import somehow... that's my next project.  
Thanks!
