### ISSUE TITLE
ZCOVERURL and ZPAGECOUNT parameters do not get populated

### ISSUE THREAD

**Issue by rensftw** [bingryan/obsidian-ibook-plugin#57]
A few parameters do not get populated when importing notes from an Apple Books entry:
`ZCOVERURL` and `ZPAGECOUNT`
I got the param names from https://github.com/bingryan/obsidian-ibook-plugin/blob/master/docs/parameters.md

Template:
```handlebars
# 📔 Book: {{library.ZSORTTITLE}}

**Book cover URL**:: {{library.ZCOVERURL}}
**Page count**:: {{library.ZPAGECOUNT}}

**Author**:: {{library.ZAUTHOR}}

**LANGUAGE**:: {{library.ZLANGUAGE}}
```

Gets rendered as:
<img width="504" alt="image" src="https://github.com/bingryan/obsidian-ibook-plugin/assets/22574186/8269e961-b6e0-421b-9812-e88691056af9">

Ideally I want to show the book cover in my Obsidian note

**Comment by bingryan** [comment]
@rensftw ZCOVERURL value is  null, so it does not display :)

**Comment by rensftw** [comment]
I tried a couple of books and both didn't have a cover URL 🤔 Must be bad metadata on the epub itself

Thanks for looking into it anyway
