### ISSUE TITLE
Can I get rid of message below:

### ISSUE THREAD

**Issue by buylife** [bingryan/obsidian-ibook-plugin#60]
Can I get rid of the message that keep showing when I open Obsidian
see here: https://ibb.co/wzP4TGP

**Comment by bingryan** [comment]
@buylife this seems to be a permissions issue with obsidian?

**Comment by buylife** [comment]
Definitely, do you think is there a way to resolve this once and for all? I'm on macOS Sonoma

**Comment by bingryan** [comment]
enable `Full Disk Access > obsidian `
