### ISSUE TITLE
The best plugin of my 2023

### ISSUE THREAD

**Issue by castlewong** [bingryan/obsidian-ibook-plugin#61]
Didn't sure about if issue should be used in this way, but... thanks for making this plugin, I am dedicated to using Obsidian and iBook, just be amazed by your plugin, all best wishes to you!

**Comment by bingryan** [comment]
> Didn't sure about if issue should be used in this way, but... thanks for making this plugin, I am dedicated to using Obsidian and iBook, just be amazed by your plugin, all best wishes to you!

cheers :beers:
