### ISSUE TITLE
Chapter titles are missing

### ISSUE THREAD

**Issue by Toastyy1** [bingryan/obsidian-ibook-plugin#66]
First of all, very useful plugin!

I'm currently using Obsidian version 1.5.8.

Using the default template, importing my highlights works fine so far, but the titles of the chapters in which the highlight occurs are missing:

![CleanShot 2024-02-23 at 12 44 50](https://github.com/bingryan/obsidian-ibook-plugin/assets/81110115/1ea081d2-3742-4738-ad42-16cdcb15725a)

I've tried it with other books too, but it didn't work with these either. Is there a quick fix to it?

Thanks in advance

**Comment by Toastyy1** [comment]
### Update:

I looked into the SQLite database where the annotations are stored. Seems like the column "ZFUTUREPROOFING5" holds chapter titles but it's always `null`.

So I guess it's not the plugin but my highlights not being stored correctly

**Comment by bingryan** [comment]
> ### Update:
> I looked into the SQLite database where the annotations are stored. Seems like the column "ZFUTUREPROOFING5" holds chapter titles but it's always `null`.
> 
> So I guess it's not the plugin but my highlights not being stored correctly

Some books may have these problems. :)
